services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Kommunikation mellem services
      - "15672:15672" # Web UI til at overvåge RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - haav

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - haav
    restart: always


  bidserviceapi:
    image: fawad23/bid-service:3.0.1
    container_name: bid-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5003
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003"
    restart: always
    networks:
      - haav

  auctionserviceapi:
    build: ./AuctionServiceAPI
    container_name: auctionserviceapi
    depends_on:
      - rabbitmq
      - loki
      - mongodb
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MONGODB_URI=mongodb://mongodb:27017
      - AUCTION_DB_NAME=AuctionServiceDb
      - AUCTION_COLLECTION_NAME=AuctionCollection
      - CATALOG_COLLECTION_NAME=CatalogCollection
    ports:
      - "5002:5002"
    restart: always
    networks:
      - haav

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - haav

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - haav
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongodata:

networks:
  haav:
