services:
  auctionserviceapi:
    build: ./AuctionServiceAPI
    container_name: auctionserviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5002:5000"
    restart: always
    networks:
      - haav


networks:
  haav:
    driver: bridge
